#!/bin/bash
echo Terminating instance...
aws ec2 terminate-instances --instance-ids i-0c0f5839b3eafb450 1>/dev/null
echo Deleting stop_instance.sh...
rm stop_instance.sh
echo Deleting restart_instance.sh...
rm restart_instance.sh
echo Deleting terminate_instance.sh...
rm terminate_instance.sh
echo Done! All scripts related to instance i-0c0f5839b3eafb450 have been deleted.
